.TH "ds.sh" "1" "" "Simon Arjuna Erat (sea)"

.SH NAME
ds.sh (0.1)

.SH SYNOPSIS
\fBds.sh\fP [options] [arguments]
.br
Example: ds.sh
.br
Where options are:
.IP "\fB-XY\fP"
does this
.IP "\fB-YX\fP"
does that

.SH DESCRIPTION
.PP
Some descriptional text

.SH LICENSE
GNU Lesser General Public License (LGPL)
.br
http://www.gnu.org/licenses/lgpl.html

.SH CONTACT
erat.simon@gmail.com
.br
http://sea.fedorapeople.org
