#!/usr/bin/env bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2015 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	
	. tui
	script_version=0.1
#
#	Title
#
	title="$OA_TITLE - GIT Handler - Clone repositry"
	tui-title "$title ($script_version)"
	#[ -f "$CONF_GIT" ] || \
	#	(tui-wait 5s "Please take care to provide all required data...";ds setup)
	DIR_CFG="$HOME/.config/dev-scripts/prjs"	# Temporary only
	CONF_GIT="$DIR_CFG/../git.conf"			# Temporary only
	# TODO :: Commment-invert the above 4 lines back when done
	source "$CONF_GIT" || ds setup
#
#	Variables
#
	if [ -z "$4" ]
	then	if [ ! -z "$1" ] && [ -d "$DIR_CFG/$1" ]
		then	LBL="$1"
		else	tui-echo "Please select the label to work with:"
			LBL=$(tui-select $(cd "$DIR_CFG";ls|$GREP -v [a-zA-Z]*\.))
		fi
	else	LBL="$4"
	fi
	[ -f "$CONF_GIT" ] && source "$CONF_GIT"
	source "$DIR_CFG/$LBL/$LBL.conf"
	source "$DIR_CFG/$LBL/git.conf" || exit 1
#
#	Display and action
#
	cd "$prj_path" || exit 1
	if $remoteOnly
	then	echo "line:$LINENO works -- already missing !!"
		echo "line:$LINENO works --==-- \$remoteOnly is $remoteOnly in $SHELL"
		pwd
		ls
		if [ -d "$prj_name" ]
		then	echo "line:$LINENO works"
			set -x
			[ -d "$prj_name/.git" ] && \
				msg="Remote only git repositry already exists" || \
				msg="Cloning remote only repositry to $prj_path/$prj_name"

			if tui-status $? "$msg"
			then	cd "$prj_name" 
				echo git pull
			else	echo git clone "$URL" "$prj_name" ; cd "$prj_name" 
			fi
		else	git clone "$URL" "$prj_name" ; cd "$prj_name" 
		fi
	else	tui-printf -S $RET_TODO "Regular project"
	fi