#!/usr/bin/env bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2015 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	
	#. tui
	#set -x
	script_version=0.1
#
#	Title
#
	title="$OA_TITLE - GIT Handler - Config repositry"
	tui-title "$title ($script_version)"
	[ -f "$CONF_GIT" ] || \
		(tui-wait 5s "Please take care to provide all required data...";ds setup)
	source "$CONF_GIT" || ds setup
#
#	Variables
#
	if [ -z "$4" ] # || [ ! -z "$LBL" ]
	then	if [ -d "$DIR_CFG/$1" ] && [ ! -z "$1" ]
		then	LBL="$1"
		else	tui-echo "Please select the label to work with:"
			LBL=$(tui-select $(cd "$DIR_CFG";ls|$GREP -v [a-zA-Z]*\.))
		fi
	else	LBL="$4"
	fi
	[ -f "$CONF_GIT" ] && source "$CONF_GIT"
	source "$DIR_CFG/$LBL/$LBL.conf"
	tConf="$DIR_CFG/$LBL/git.conf"
#
#	Action & Display
#
	cd "$prj_path/.git"
	tui-cat config
	tui-echo TODO
	#tui-conf-get -l config
	#tui-conf-editor config