#!/bin/bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	
	script_version=0.1
#
#	Title
#
	title="$OA_TITLE - GIT Handler - Status"
	tui-title "$title ($script_version)"
	[[ -f "$CONF_GIT" ]] || \
		(tui-wait 5s "Please take care to provide all required data...";ds setup)
	source "$CONF_GIT" || exit 1
	TMP=$DIR_BASE/tmp.tmp
#
#	Variables
#
	if [[ -z "$4" ]] # || [[ ! -z "$LBL" ]]
	then	if [[ -d "$DIR_CFG/$1" ]]
		then	LBL="$1"
		else	tui-echo "Please select the label to work with:"
			select LBL in $(cd "$DIR_CFG";ls|grep -v \.);do break;done
		fi
	else	LBL="$4"
	fi
	source "$DIR_CFG/$LBL/$LBL.conf"
	source "$DIR_CFG/$LBL/git.conf"
	
	cd "$prj_path"
	oLC_ALL="$LC_ALL"
	export LC_ALL=C
	str="$(git status)"
	list_add=""
	list_del=""
	list_mod=""
		
	# has changed
	echo "$str" | \
		grep -q mod && \
		list_mod=$(echo "$str"|\
			grep ^mod|\
			awk '{print $2}')
	
	# Was removed
	echo "$str" | \
		grep -q del && \
		list_del=$(echo "$str"|\
			grep ^del|\
			awk '{print $2}')
	
	# Is added
	len=0
	len=$(cat "$TMP"|wc -l)
	len=$((len+1))
	if echo "$str"|grep -A$len "git add <" |grep -v \"  > "$TMP"
	then	echo "$str"|grep ^untra | awk '{print $3}' >> "$TMP"
		list_add=$(cat "$TMP")
	fi
#
#	Display & Action
#
	tmp="$list_add$list_del$list_mod"
	tmp="$list_add $list_del $list_mod"
	#tmp=""
	if [[ "" = "$(echo $tmp)" ]]
	then	tui-echo "Nothing to do" "commit maybe??"
	else	tui-echo "Got some work to do:" "$(echo $tmp)"
		##
		## TODO
		##	PSM für files/status
		## TODO
		##
		if tui-yesno "Do you want to 'semi-auto' do these now?"
		then	# TODO handling for remove / add
			tui-status 0 "Ok, lets get it started."
			
		else	tui-status 0 "OK, you do it manualy then..."
		fi
	fi
#
#	Exit
#
	export LC_ALL="$oLC_ALL"
