#!/bin/bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014-2015 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	
	script_version=0.7.4
#
#	Title
#
	title="$OA_TITLE - Kickstart - Make an iso image"
	tui-title "$title ($script_version)"
	source /etc/tui/status.conf
	source /etc/tui/tui.conf
	source /etc/tui/commands.conf
#
#	Variables
#
	LOG=$LOG_LIVECD
	NONVERBOSE="--quiet"
	beVerbose=false
	ov=false
	oPWD=$(pwd)
	do32bit=false
	
	case $# in
	5)	shift 2 ;;
	esac
	
	NONVERBOSE="--quiet --logfile=$LOG"
	while getopts "v36h" opts
	do 	case $opts in
		3)	do32bit=true	; ov=true ;;
		6)	do32bit=false	; ov=true ;;
		v)	beVerbose=true
			NONVERBOSE=""
			;;
		esac
	done
	shift $(($OPTIND - 1))
	
	if [[ -z "$4" ]] # || [[ ! -z "$LBL" ]]
	then	if [[ -d "$DIR_CFG/$1" ]]
		then	LBL="$1"
		else	tui-echo "Please select the label to work with:"
			select LBL in $(cd "$DIR_CFG";ls|grep -v \.);do break;done
		fi
	else	LBL="$4"
	fi
	source "$DIR_CFG/$LBL/$LBL.conf"
	source "$DIR_BASE/livecd.conf"
	source "$DIR_CFG/$LBL/livecd.conf"

	# Exit if no kickstart file was found
	[[ -f "$kickstart" ]] ; tui-status $? "$kickstart exists" || exit 1
#set -x	
	# Create STRING according to ARCH
	[[ -z "$arch_style" ]] && \
		arch_style=kernel && \
		tui-conf-set "$DIR_CFG/$LBL/livecd.conf" arch_style $arch_style
	
	if $ov
	then	# User wants specific ARCH
		$do32bit_ov && \
			ARCH=32 || \
			ARCH=64
		do32bit=$do32bit_ov
	else	# Dynamicly reckognize which ARCH
		# Depeing on preset
		if $do32bit
		then	ARCH=32
		else	uname -m | grep -q 64  && \
				ARCH=64 || \
				ARCH=32
		fi
	fi
	tui-status 111 "Building \"$prj_label\" as $ARCH bit iso."
	
	# Automaticly generate identifier string as defined the the projects livecd.conf
	case $arch_style in
	number)		ARCH=${ARCH}bit	;;
	kernel)		str="$(uname -r)"
			if [[ x86_64 -eq $(uname -m) ]] && $do32bit
			then	str=${str/$(uname -m)/i686}
			fi
			# Remove fc$RELEASEVER
			ARCH="${str/.fc[1-9][0-9]/}"
			;;
	esac
	
	# Append the string to the label and title
	prj_label+="_${ARCH}"
	prj_title+=" (${ARCH})"
	
	# Generate the tempdir string
	[[ -z "$prj_tempdir" ]] && \
		prj_tempdir="/mnt/tmp/${prj_label}"
	cmd_tmpdir="--tmpdir=\"$prj_tempdir/$prj_label\""
	
	$do32bit && \
		PRE="setarch linux32" || \
		PRE=""
#
#	Display
#
	cmd_post="chown $USER:$USER ${prj_label}.iso"
	$beVerbose && \
		verboseString="" || \
		verboseString=" 2>>\"$LOG\" 1>>$LOG"
		#verboseString="1>>$LOG 2>>\"$LOG\" > \"$TUI_TEMP_FILE\""
	
	# OLD
	#sudo grep -q $USER /etc/sudoers && \
	#	cmd="sudo $PRE livecd-creator $NONVERBOSE -c \"$kickstart\" -t \"$prj_title\" -f \"$prj_label\" --releasever=$prj_release $cmd_tmpdir $verboseString && sudo $cmd_post" || \
	#	cmd="su -c \"$PRE livecd-creator $NONVERBOSE -c \\\"$kickstart\\\" -t \\\"$prj_title\\\" -f \\\"$prj_label\\\" --releasever=$prj_release $cmd_tmpdir $verboseString && $cmd_post\""
	# NEW
	tui-bol-sudo && \
		cmd="sudo $PRE livecd-creator $NONVERBOSE -c \"$kickstart\" -t \"$prj_title\" -f \"$prj_label\" --releasever=$prj_release $cmd_tmpdir $verboseString && sudo $cmd_post ; RET=\$? ; export RET" || \
		cmd="tui-echo \"Please provide the root password:\";su -c \"$PRE livecd-creator $NONVERBOSE -c \\\"$kickstart\\\" -t \\\"$prj_title\\\" -f \\\"$prj_label\\\" --releasever=$prj_release $cmd_tmpdir $verboseString && $cmd_post; RET=\$?;export RET\""
		
#set +x ; exit	
	cd "$prj_path"
	optVerb=""
	if $beVerbose
	then	cmd="${cmd/$verboseString/}"
		tui-echo "Executing:" "$cmd"
		eval $cmd
		optVerb="-v"
		RET=$?
	else	echo "$cmd" > "$TUI_TEMP_FILE.cmd"
		echo "${cmd/$verboseString/}" >> "$LOG"
		tui-bgjob "$TUI_TEMP_FILE.cmd" "Building $prj_name ($prj_label.iso) live image...   (~30-60m)" "Built $prj_name ($prj_path/$prj_label.iso) live image."
		RET=$?
	fi
		
#set -x	
	if [ 0 -eq $RET ]
	then	# Its already been chown'ed
		tui-bol-dir "$prj_outpath/" && \
			msg="$prj_outpath exists." || \
			msg="$prj_outpath does NOT exist."
		tui-log $optVerb -t "$LOG""$msg"
		
		if [ -f "$PWD/${prj_label}.iso" ]
		then	tui-log $optVerb -t "$LOG" "Found: $PWD/${prj_label}.iso"
			target="$prj_outpath/${prj_label}.iso"
			RET=1
			mv "$PWD/${prj_label}.iso" "$prj_outpath/" && \
				tui-log $optVerb -t "$LOG" "Successfully moved to $target" && \
				RET=0 || \
				tui-log $optVerb -t "$LOG" "Failed to move to $target"
		else	tui-log $optVerb -t "$LOG" "NOT found: $PWD/${prj_label}.iso"
		fi
		tui-status $? "Moved to $prj_outpath/" "$prj_label.iso"
	elif [ false = $beVerbose ]
	then	tui-yesno "Do you want to see the $LOG for details?" && tui-edit "$LOG"
	fi
	
	# Clean up temporary data, specialy if it failed....
	if [ ! -z "$prj_tempdir" ] 
	then 	cd "$prj_tempdir"
		tui-log $optVerb -t "$LOG" "Changed to: $prj_tempdir"
		RET2=1
		tui-bol-sudo && \
			(sudo rm -fr * ; RET2=$? ; export RET2 ) || \
			su -c "rm -fr * ; RET2=\$? ; export RET2"
		tui-status $RET2 "Removed tempdirectories: $prj_tempdir"
	fi
	cd "$oPWD"
	exit $RET