#!/bin/bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	
	script_version=0.2
#
#	Title
#
	title="$OA_TITLE - Kickstart - Make an iso image"
	tui-title "$title ($script_version)"
#
#	Variables
#
	if [[ -z "$4" ]] # || [[ ! -z "$LBL" ]]
	then	if [[ -d "$DIR_CFG/$1" ]]
		then	LBL="$1"
		else	tui-echo "Please select the label to work with:"
			select LBL in $(cd "$DIR_CFG";ls|grep -v \.);do break;done
		fi
	else	LBL="$4"
	fi
	source "$DIR_CFG/$LBL/$LBL.conf"
	source "$DIR_BASE/livecd.conf"
	source "$DIR_CFG/$LBL/livecd.conf"
	for arg in "${@}";do
	case "$arg" in
	"-3")	do32bit=true	;;
	"-6")	do32bit=false	;;
	esac
	done
	if [[ -z "$do32bit" ]]
	then	# Not set, use system arch
		uname -m | grep -q 64  && \
			ARCH=32 || \
			ARCH=64
	else	$do32bit && \
			ARCH=32 || \
			ARCH=64
	fi
	[[ -z "$prj_tempdir" ]] && \
		cmd_tmpdir="--tmpdir=\"/mnt/tmp/${prj_label}_${ARCH}\"" || \
		cmd_tmpdir="--tmpdir=\"$prj_tempdir\""
	[[ ! -z "$do32bit" ]] && \
		$do32bit && \
		PRE="setarch linux32" || \
		PRE=""
	
	prj_label+="_${ARCH}bit"
	prj_title+=" ${ARCH}bit"
#
#	Display
#
	# livecd-creator -c "$kickstart" -t "$prj_title" -f "$prj_label" --releasever=$prj_release $cmd_tmpdir
	cmd_post="chown $USER:$USER ${prj_label}.iso"
	sudo grep -q $USER /etc/sudoers && \
		cmd="sudo $PRE livecd-creator -c \"$kickstart\" -t \"$prj_title\" -f \"$prj_label\" --releasever=$prj_release $cmd_tmpdir ; sudo $cmd_post" || \
		cmd="su -c \"$PRE livecd-creator -c \\\"$kickstart\\\" -t \\\"$prj_title\\\" -f \\\"$prj_label\\\" --releasever=$prj_release $cmd_tmpdir ; $cmd_post\""
	
	[[ -f "$kickstart" ]] && tui-status $? "$kickstart exists"
	
	cd "$prj_outpath"
	tui-echo "Executing:" "$cmd"
	eval $cmd
	cd "$OLDPWD"
	
	#exit
	#tui-status $? "Built $prj_name" && \
	#	mv "$prj_label.iso" "$prj_outpath/"
