#!/bin/bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	Descriptional text here...
#	and here...
#
#
#
#	Variables
#
	set +x #
	tui-header "READING $CONF_SSH" "its not the first time i do this check"
	cat $CONF_SSH
	tempfile=$HOME/.cache/ssh-cmd
	if [[ ! -f $CONF_SSH ]]
	then	tui-status 1 "No configuration found!"
		tui-yesno "Setup SSH now?" && \
			ds prj ssh setup || \
			exit 1
	fi
	source $CONF_SSH
#
#	Action
#
	[[ -z $COMMENT ]] && nocom="-C ''" || nocom="-C \"$COMMENT\""
	[[ -z $PASSWORD ]] || nopw="-N \"$PASSWORD\""
	
	if [[ -f $ssh_file ]]
	then	tui-yesno "You already have an SSH keyfile, overwrite?" && \
			rm -f $ssh_file || \
			exit 1
	fi
	
	cat > $tempfile << EOF
	ssh-keygen  -b  $BIT \
			$nopw \
			$nocom \
			-f $ssh_file > ${tempfile}2
EOF
	tui-bgjob "$tempfile" "Generating SSH file..." "Generated SSH file."
	if [[ 0 -eq $? ]]
	then	# Save additional info...
		 grep randomart ${tempfile}2 -A 11|grep -v random > ${ssh_file}-randomart
		 grep fingerprint ${tempfile}2 -A 1|grep -v "fingerprint" > ${ssh_file}-fingerprint
	fi
# TODO remove comment when all is working
#	rm $tempfile ${tmpfile}2
