#!/bin/bash
#
#	Desription:	Create ftp config file for project
#	Lisence:        GPL v3
#	Author:         Simon A. Erat (sea), erat.simon æ gmail.com
#	Release Date:   2012.11.16
#	Changed Date:	2013.08.28
	script_version=0.5
#
#	Title
#
	title="sea's FTP Handler - New"
	sT "$title ($script_version)"
#
#	Variables
#
	lbl=""
	[ ! -z $4 ] && \
		[ -f "$SEA_DEV_DIR/$4/conf" ] && \
		lbl="$4"
	[ "" = "$lbl" ] && \
		sP "Please select a LABEL to use:" && \
		lbl=$(PRJ_Select) && \
		sE "Selected $lbl" "$DONE"
	source "$SEA_DEV_DIR/$lbl/conf"
#
#	Display
#
	REPO_New "$lbl"
	ReportStatus $? "Created repo configuration for $prj_name"
