#!/usr/bin/env bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014-2015 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	
	script_version=0.5.1
#
#	Title
#
	title="$OA_TITLE - RPM Handler - Configure RPM and add specfile"
	tui-title "$title ($script_version)"
#
#	Variables
#
	if [ -z "$4" ] # || [[ ! -z "$LBL" ]]
	then	if [[ -d "$DIR_CFG/$1" ]]
		then	LBL="$1"
		else	tui-echo "Please select the label to work with:"
			select LBL in $(cd "$DIR_CFG";ls|grep -v \.);do break;done
		fi
	else	LBL="$4"
	fi
	
	oPWD="$(pwd)"
	rpm_builddir=""
	[ -f "$CONF_RPM" ] && source "$CONF_RPM"
	source "$DIR_CFG/$LBL/$LBL.conf" ; cd "$prj_path"
	tConf="$DIR_CFG/$LBL/rpm.conf"
#
#	Display
#
	# Create the file if not existent
	[[ -f "$tConf" ]] || \
		echo "# RPM configuration for $prj_name" > "$tConf"
	
	# TODO, use custom templates, according to remoteOnly?
	specfile="$prj_path/$prj_name.spec"
	rpmdev-newspec "$prj_name" > /dev/zero
	RET=$?
        [ $RET -eq 2 ]] && RET=0
	tui-status $RET "Created specfile ($specfile)"
	tui-conf-set "$tConf" specfile "\$prj_path/\$prj_name.spec"
	source "$tConf"
	
	tui-echo "What is your default build target?"
	if $remoteOnly
	then	tui-yesno "Will \"$prj_name\" be a 'noarch' project?" && \
			opt=ba || opt=bs
	else	bOpt=$(tui-select all sources packages)
		case $bOpt in
		all)		opt="ba"	;;
		sources)	opt="bs"	;;
		packages)	opt="bb"	;;
		esac
	fi
	tui-conf-set "$tConf" opt "$opt"
	
	
	if $remoteOnly
	then	LIST=$(grep -i "source" "$specfile"|awk '{print $1}')
		if [[ -f "$DIR_CFG/$LBL/git.conf" ]]
		then	tui-echo "Please select what shall be used to retrieve code:"
			select SOURCE in git $LIST ;do break;done
		elif [[ "$(echo $LIST)" = "$(echo $LIST|awk '{print $1}')" ]]
		then	SOURCE="$(echo $LIST)"
		else	tui-echo "Please select which source shall be used:"
			grep -i ^source "$specfile"|while read src val;do tui-echo "${src/:/}" "$val";done
			select SOURCE in $LIST;do break;done
		fi
		tui-conf-set "$tConf" downloadMode "${SOURCE/:/}"
	fi
	
	tui-yesno "Clean builddir after each new build?" && \
		tui-conf-set "$tConf" rpm_cleandir_after "true" || \
		tui-conf-set "$tConf" rpm_cleandir_after "false"
	
	if [[ ! -f "$CONF_RPM" ]]
	then	touch "$CONF_RPM"
		echo "# Shared RPM configuration among all projects" > "$CONF_RPM"
		tui-yesno "Do you have defined a custom builddir?" && \
			tDir=$(tui-read "Please type the full path:") && \
			tui-conf-set "$CONF_RPM" rpm_builddir "$tDir" || \
			tui-conf-set "$CONF_RPM" rpm_builddir "\$HOME/rpmbuild"
	
		tui-yesno "Clean builddir before each new build?" && \
			tui-conf-set "$CONF_RPM" rpm_cleandir "true" || \
			tui-conf-set "$CONF_RPM" rpm_cleandir "false"
	fi
	
	[[ ! -z "$specfile" ]] && \
		tui-yesno "Edit the specfile now?" && \
		tui-edit "$specfile"
	
	cd "$oPWD"
	tui-status $RET "Created specfile and rpm config for: $prj_name"
	exit $RET
