#!/usr/bin/env bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014-2015 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	
	script_version=0.4
#
#	Title
#
	title="$OA_TITLE - RPM Handler - Edit specfile"
	tui-title "$title ($script_version)"
#
#	Variables
#
	if [ -z "$4" ] # || [[ ! -z "$LBL" ]]
	then	# Its not called like: ds prj rpm make LBL, but ./make [LBL]
		if [ -d "$DIR_CFG/$1" ] && [ ! -z "$1" ]
		then	LBL="$1"
		else	tui-echo "Please select the label to work with:"
			LBL=$(tui-select $($LS "$DIR_CFG"))
		fi
	else	LBL="$4"
	fi
	source "$CONF_RPM"
	source "$DIR_CFG/$LBL/$LBL.conf"
	source "$DIR_CFG/$LBL/rpm.conf"
#
#	Display
#
	tui-edit "$specfile"
