#!/bin/bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	
	. tui
	. $HOME/.config/dev-scripts/dev-scripts.conf
	. $HOME/.config/dev-scripts/rpm.conf
	script_version=0.3
#
#	Title
#
	title="$OA_TITLE - RPM Handler - List built packages"
	[ ! list = "$(basename $0)" ] && tui-title "$title ($script_version)"
	oPWD="$(pwd)"
#
#	Variables
#
	OF=""
	[ -z "$3" ] || shift 3
	
	if [ -z "$1" ] # || [[ ! -z "$LBL" ]]
	then	tui-echo "Please select the label to work with:"
		LBL=$(tui-select $(cd "$DIR_CFG";ls))
	else	if [ -d "$DIR_CFG/$1" ]
		then	LBL="$1"
			OF="$2"
		fi
	fi
	if [ ! -z "$OF" ]
	then	# Its not empty
		set -x
		d=$(dirname "$OF")
		b=$(basename "$OF")
		[ "$d" = "$b" ] && OF="$oPWD/$OF"
		[ "." = "$d" ] && OF="$oPWD/$OF"
		set +x
	fi
	
	TASK="rpm mock"
	
	#source "$CONF_RPM"	# Das failt -- tui-browser issue :(
	source "$DIR_CFG/../rpm.conf"
	source "$DIR_CFG/$LBL/$LBL.conf"
	source "$DIR_CFG/$LBL/rpm.conf"
	source "$DIR_CFG/$LBL/git.conf"
	#source "$CONF_MOCK"
	VER=$(grep Version "$specfile"|awk '{print $2}')
	
	MOCK="$DIR_CFG/$LBL/mock.conf"
	if [ -f "$MOCK" ]
	then	source "$MOCK"
		source "$DIR_CFG/../mock.conf"
		TASK+=" mock"
	fi
#
#	Display
#
	#set -x
	
	
	#echo "$rpm_builddir" ; exit
	
	for task in $TASK
	do	case $task in
		rpm)
			if [ -z "$rpm_builddir" ]
			then	tui-status 1 "Path not found: $rpm_builddir"
				exit $?
			fi
			cd "$rpm_builddir/"
			list=$(find |$GREP rpm$|$GREP "$prj_name"|$GREP "$prj_name"|$GREP \\.rpm$ 2>/dev/zero) 2>/dev/zero
			
			if [ ! -z "$OF" ]
			then	# This works
				[ -d "$(dirname $OF)" ] || mkdir -p "$(dirname $OF)"
				[ -f "$OF" ] && rm -f "$OF"
				touch "$OF"
				echo "$list" > "$OF"
			else	# But here is no output
				
				if [[ -z "$list" ]]
				then	tui-status 1 "No packages for \"$prj_name\" found..."
				else	echo "$list"|while read line;do tui-echo "${line:2}";done
				fi
				#find $rpm_builddir|$GREP $prj_name|$GREP rpm$
			fi
			;;
		mock)	
			if [ ! -d /var/lib/mock ]
			then	tui-status 1 "Path not found: /var/lib/mock"
				exit $?
			fi
			cd /var/lib/mock
			list=$(find |$GREP rpm$|$GREP "$prj_name"|$GREP "$prj_name"|$GREP \\.rpm$ 2>/dev/zero) 2>/dev/zero
			
			if [ ! -z "$OF" ]
			then	# This works
				[ -d "$(dirname $OF)" ] || mkdir -p "$(dirname $OF)"
				[ -f "$OF" ] && rm -f "$OF"
				touch "$OF"
				echo "$list" > "$OF"
			else	# But here is no output
				
				if [ -z "$list" ]
				then	tui-status 1 "No packages for \"$prj_name\" found..." > /dev/zero
				else	#echo "$list"|while read line;do tui-echo "${line:2}";done
					tui-list -n "$list"
				fi
				#find $rpm_builddir|$GREP $prj_name|$GREP rpm$
			fi
			;;
		esac
	done
	cd "$oPWD"
