#!/bin/bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014-2015 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	
	. tuirc
	. $HOME/.config/dev-scripts/dev-scripts.conf
	. $HOME/.config/dev-scripts/rpm.conf
	. /usr/share/dev-scripts/incl/*
	script_version=0.6
#
#	Title
#
	title="$OA_TITLE - RPM Handler - List built packages"
	[ ! list = "$(basename $0)" ] && tui-title "$title ($script_version)"
	oPWD="${PWD_OLD:-$PWD}"
#
#	Variables
#
	OF=""
#	echo "prj1$1 rpm2$2 list3$3 lbl4$4"
	[ -z "$4" ] || shift 3
	dolistMock=false
	doListSource=false
	doOnlyMock=false
	str_source=""
	ME=list
	
	while getopts hmMs opt
	do 	case $opt in
		h)	echo "Usage: ds prj rpm list [-mMs] [LBL]"
			exit 99
			;;
		m)	dolistMock=true
			;;
		M)	dolistMock=true
			doOnlyMock=true
			;;
		s)	doListSource=true
			str_source="| $GREP \\.src\\."
			;;
		esac
	done
	shift $(($OPTIND - 1))
	
	if [ -z "$1" ] # || [[ ! -z "$LBL" ]]
	then	tui-echo "Please select the label to work with:"
		LBL=$(tui-select $(cd "$DIR_CFG";ls))
	else	if [ -d "$DIR_CFG/$1" ]
		then	LBL="$1"
			OF="$2"
		fi
	fi
	#set +x
	
	if [ ! -z "$OF" ]
	then	# Its not empty
		#set -x
		d=$(dirname "$OF")
		b=$(basename "$OF")
		[ "$d" = "$b" ] && OF="$oPWD/$OF"
		[ "." = "$d" ] && OF="$oPWD/$OF"
		
		[ -d "$(dirname $OF)" ] || mkdir -p "$(dirname $OF)"
		[ -f "$OF" ] && rm -f "$OF"
		touch "$OF"
		#set +x
	fi
	
	TASK="rpm "
	
	#source "$CONF_RPM"	# Das failt -- tui-browser issue :(
	source "$DIR_CFG/../rpm.conf"
	source "$DIR_CFG/$LBL/$LBL.conf"
	[ -f "$DIR_CFG/$LBL/rpm.conf" ] && source "$DIR_CFG/$LBL/rpm.conf"
	#source "$DIR_CFG/$LBL/git.conf"
	VER=$(grep Version "$specfile"|awk '{print $2}')
	
	MOCK="$DIR_CFG/$LBL/mock.conf"
	if [ -f "$MOCK" ]
	then	source "$MOCK"
		source "$CONF_MOCK"
		source "$DIR_CFG/../mock.conf"
	fi
	# Replace task if dolistMock is 'true' and project contains a mock module
	#set -x
	if $dolistMock
	then	if [ -f "$MOCK" ]
		then	$doOnlyMock && \
				TASK="mock" || \
				TASK+=" mock"
		fi
	fi	
#
#	Display
#
	#set -x
	for task in rpm #$TASK
	do	case $task in
		rpm)
			if [ -z "$rpm_builddir" ] || [ ! -d "$rpm_builddir" ]
			then	if ! rpmdev-setuptree
				then	tui-status 1 "Path not found: $rpm_builddir"
					exit $?
				fi
			fi
			
			cd "$rpm_builddir"
			list=""
			$doListSource && \
				list=$(find |$GREP "$prj_name"|$GREP \.rpm | $GREP \.src\. |$GREP -v \.sh$ 2>/dev/zero) # >$OF")
			list+=$( find |$GREP "$prj_name"|$GREP \.rpm | $GREP -ve \.sh$ -ve \.src\. 2>/dev/zero) # >$OF" )
			
			if [ ! -z "$OF" ]
			then	# This works
				newlist=""
				for l in $list;do
					newlist+=" ${l/\./$rpm_builddir}\n"
				done
				printf "$newlist" | sort -uV >> "$OF"
			else	# But here is no output
				tui-title "$title ($task)"
				if [ -z "$list" ]
				then	tui-status 1 "No packages for \"$prj_name\" found..."
				else	tui-list -n $list
				fi
				#find $rpm_builddir|$GREP $prj_name|$GREP rpm$
			fi
			;;
		mock)	
			if [ ! -d /var/lib/mock ]
			then	tui-status 1 "Path not found: /var/lib/mock"
				exit $?
			fi
			cd /var/lib/mock
			
			if tui-bol-sudo
			then	$doListSource && \
					list=$(sudo find |$GREP result|$GREP "$prj_name"|$GREP \.rpm | $GREP \\.src\\. 2>/dev/zero) || \
					list=$(sudo find |$GREP result|$GREP "$prj_name"|$GREP \.rpm  2>/dev/zero)
			else	$doListSource && \
					list=$(su -c "find |$GREP $prj_name|$GREP result|$GREP \.rpm | $GREP \\.src\\. 2>/dev/zero") 2>/dev/zero || \
					list=$(su -c "find |$GREP $prj_name|$GREP result|$GREP \.rpm 2>/dev/zero") 2>/dev/zero
			fi
			
			if [ ! -z "$OF" ]
			then	# This works
				newlist=""
				varlibmock=/var/lib/mock
				for l in $list;do
					newlist+=" ${l/./$varlibmock}" #\n"
				done
				printf "$newlist" | sort -uV >> "$OF"
			else	# But here is no output
				tui-title "$title ($task)"
				if [ -z "$list" ]
				then	tui-status 1 "No packages for \"$prj_name\" found..." #> /dev/zero
				else	#echo "$list"|while read line;do tui-echo "${line:2}";done
					tui-list -n $list
				fi
				#find $rpm_builddir|$GREP $prj_name|$GREP rpm$
			fi
			;;
		esac
	done
	#set +x
	cd "$oPWD"
