#!/bin/bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	
	script_version=0.2
#
#	Title
#
	title="$OA_TITLE - RPM Handler - Build package"
	tui-title "$title ($script_version)"
#
#	Variables
#
	if [[ -z "$4" ]] # || [[ ! -z "$LBL" ]]
	then	if [[ -d "$DIR_CFG/$1" ]]
		then	LBL="$1"
		else	tui-echo "Please select the label to work with:"
			select LBL in $(cd "$DIR_CFG";ls|grep -v \.);do break;done
		fi
	else	LBL="$4"
	fi
	source "$DIR_CFG/$LBL/$LBL.conf"
	source "$DIR_CFG/$LBL/rpm.conf"
	OPTS="-ba"
	VER=$(grep Version "$specfile"|awk '{print $2}')
	TARBALL="$prj_name-$VER.tar.gz"
	DEST="$rpm_builddir"
	#echo $DEST ; exit
#
#	Display
#
	
	# Create tarball if missing
	if [[ ! -f "$DEST/SOURCES/$TARBALL" ]]
	then	cd "$prj_path/.."
		tui-tar "$prj_name"
		mv "$prj_name.tar.gz" "$DEST/SOURCES/$TARBALL"
		cd "$prj_path"
	fi
	ln -sf "$specfile" "$DEST/SPECS/$(basename $specfile)"
	
	rpmbuild $OPTS "$specfile"
	
	if $useFAS
	then	source $HOME/.config/fas/fas.conf
		DEST="$FAS_REVIEW/$prj_name"
		TMP="$DIR_BASE/tmp.tmp"
		ds prj rpm list $LBL "$TMP"
		[[ -d "$DEST" ]] || mkdir -p "$DEST"
		rpmdev-setuptree
		cat "$TMP"|while read line;do
			tui-echo "Moved to $DEST:" "$(basename $line)"
			mv "$line" "$DEST"/
		done
	fi
