#!/bin/bash
#
#	Desription:	Create ftp config file for project
#	Lisence:        GPL v3
#	Author:         Simon A. Erat (sea), erat.simon æ gmail.com
#	Release Date:   2012.11.16
#	Changed Date:	2013.08.28
	script_version=0.5
#
#	Title
#
	title="sea's FTP Handler - New"
	sT "$title ($script_version)"
#
#	Variables
#
	lbl=""
#
#	Display
#
	[ ! -z $5 ] && \
		[ -d $SEA_DEV_DIR/$5 ] && \
		lbl=$5
	[ "" = "$lbl" ] && \
		sP "Please select a LABEL to use:" && \
		lbl=$(PRJ_Select) && \
		sE "Selected $lbl" "$DONE"
	FTP_New "$lbl"
	ReportStatus $? "Created ftp configuration for $prj_name"
