#!/bin/bash
#
#	Desription:	Handles GIT Commands - Change
#	Lisence:        GPL v3
#	Author:         Simon A. Erat (sea) ; < < erat . simon @ gmail . com >
#	Created:	2013.08.24
#	Changed:	2013.08.28
	script_version=0.4
#
#	Title
#
	title="sea's GIT Handler - Change"
	sT "$title ($script_version)"
#
#	Variables
#
	lbl="$4"
	new="$5"
	args=( "$4" "$5" "$6" "$7" "$8" )
	for arg in "${args[@]}" ;do
		[ "-h" = "$arg" ] && \
			echo -e "change ($script_version)
				\rUsage: st dev git change [LABEL] [NEWBRANCH]
				\rCheckout NEWBRANCH of project LABEL
				\r" && return 99
	done
#
#	Display
#
	[ "" = "$lbl" ] && \
		sE "Please select a project where to change branch:" && \
		select lbl in $(PRJ_Select);do break;done
	source "$SEA_DEV_DIR/$lbl/conf"
	sE "Selected project:" "$prj_name"
	cd "$prj_path"
	current=$(GIT_Branch_List "$lbl"|awk '{print $1}')
	sE "Current branch:" "$current"
	
	if [ ! -f "$SEA_DEV_DIR/$lbl/git" ]
	then	ask "Add a GIT module to $prj_name?" && \
			GIT_New "$lbl"
		return 1
	fi
	
	if [ "" = "$new" ]
	then	sE "Select the branch to change to:"
		select new in $(GIT_Branch_List "$lbl");do break;done
	fi
	
	#GIT_Req_Commit "$lbl" && GIT_Commit "$lbl" -c
	git add .
	GIT_Change "$lbl" "$new"
	ReportStatus $? "Changed $prj_name from $current to $new"
	cd "$OLDPWD"
