#!/usr/bin/env bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014-2015 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	
	script_version=0.4
#
#	Title
#
	title="$OA_TITLE - Edit project configuration"
	tui-title "$title ($script_version)"
#
#	Variables
#
	. tuirc
	if [ -z "$3" ] # || [ ! -z "$LBL" ]
	then	if [ -d "$DIR_CFG/$1" ] && [ ! -z "$1" ]
		then	LBL="$1"
		else	tui-echo "Please select the label to work with:"
			LBL=$(tui-select $(cd "$DIR_CFG";ls|$GREP -v [a-zA-Z]*\.))
		fi
	else	LBL="$3"
	fi
	[ -z "$LBL" ] && \
		tui-printf -S 1 "Something went wrong.. missing label..." && \
		exit 1 || \
		source "$DIR_CFG/$LBL/$LBL.conf"
#
#	Display
#
	tui-edit cd "$DIR_CFG/$LBL"/*conf
