#!/bin/bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	
	script_version=0.2
	#Changed:	2015.12.30
#
#	Title
#
	title="$OA_TITLE - List project modules"
	tui-title "$title ($script_version)"
#
#	Variables
#
	LBL=""
	cd "$DIR_CFG"
	[[ -z "$LBL" ]] && list=($(ls|grep -v "\."))
#
#	Display
#
	items=$(\ls --ignore default* --ignore edit --ignore list $DS_DIR_MENU/prj)
	for L in "${list[@]}";do
		S=$(tui-conf-get "$L/$L.conf" "prj_name")
		uses=""
		for T in $items #build rpm mock livecd git
		do	[ "$T" = "ks" ] && T=livecd
			[[ -f "$L/$T.conf" ]] && \
				uses+=" $T"
		done
		tui-print -E "$S ($L) uses:" "$uses"
	done
