#!/bin/bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	Variables
#
	[[ -z "$2" ]] && LBL="" || LBL="$2"
	[[ -z $LBL ]] || str=" ($LBL)"
	TASK_LIST=$(cd /usr/share/dev-scripts/menu/prj;ls -l|grep ^d|awk '{print $9}'|sed s,ks,livecd,g)	#|grep -v git
	LIST=""
#
#	Display & Action
#
	tui-title "Make all project tasks$str"
	if [[ -z "$LBL" ]]
	then	tui-echo "Please select a project to make:"
		select LBL in $(cd "$DIR_CFG";ls);do break;done
		tui-status $? "Selected: $LBL" || exit $?
	fi
	old="$(pwd)"
	cur="$DIR_CFG/$LBL"
	source "$cur/$LBL.conf"
	cd "$cur"
	for L in $TASK_LIST;do 
		#echo $L
		[[ -f "$L.conf" ]] && LIST+=" $L"
	done
	#echo $LIST
	
	cd "$old"
	
	for T in $LIST;do
		cmd="$(pwd)/prj"
		add=""
		tui-title "Task ($T) for '$LBL' with: $(echo $LIST)"
		
		case $T in
		rpm)	add="/rpm/make"		;;
		livecd)	add="/ks/make" 		;;	
		git)	tui-echo "TODO: $T"	;;
		*)	tui-echo "TODO: $T"	;;
	#	ks)	tui-echo "TODO: $T"
	#		;;	
		esac
		
		#echo $cmd$add
		[[ -z "$add" ]] || $cmd$add $LBL
	done
