#!/bin/bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License (GPL) as published
# by the Free Software Foundation, either version shipped with the script, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License (GPL) for more details.
#
# You should have received a copy of the GNU General Public License (LGPL)
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	File:		setup
#	Author: 	Simon Arjuna Erat (sea)
#	Contact:	erat.simon@gmail.com
#	License:	GNU General Public License (LGPL)
#	Created:	2014.09.13
#	Changed:	2014.11.29
	script_version=0.4
	TITLE="$OA_TITLE - Setup"
#	Description:	Set up the project main settings
#			
#
#
#	Script Environment
#
	ME="${0##*/}"				# Basename of setup
	ME="${ME/.sh/}"				# Cut off .sh extension
	APP=dev-scripts
	tempfile="$CONFIG_DIR/$APP.tmp"		# Tempfile
	CONFIG_DIR="$HOME/.config/dev-scripts"
	CONFIG="$CONFIG_DIR/dev-scripts.conf"
#
#	Help text
#
	this_dir="$CONFIG_DIR/gitinfo"
	write_git_info() { #
	#
	#
		[[ -d "$this_dir" ]]  || mkdir -p "$this_dir"
		
		for T in gh sf
		do	# Gather info of each file
			
			case $T in
			gh)	# Git Hub
				name=GitHub
				URL="https://github.com"
				URL2="$URL/new"
				;;
			sf)	# Source Forge
				name=SourceForge
				URL="http://sourceforge.net/projects"
				URL2="$URL/p/add_project"
				;;
		#	gh)	# 
				
		#		;;
		#	gh)	# 
				
		#		;;
			esac
			user=$(tui-read "Please enter your $name accountname:")
			cat > "$this_dir/$name" << EOF
name=$name
user=$user
URL=\"$URL\"
URL_NEW=\"$URL2\"
EOF
		done
	}
	
	[[ -d "$this_dir" ]] || write_git_info
#
#	Default configuration
#
	[[ -d "$CONFIG_DIR" ]] || mkdir -p "$CONFIG_DIR"
	[[ -f "$CONFIG" ]] || cat > "$CONFIG" << EOF
# $ME configuration
DIR_PRJS=\"\$HOME/Projects\"
DIR_BASE=\"\$HOME/.config/dev-scripts\"
DIR_CFG=\"\$DIR_BASE/prjs\"
EOF
	source "$CONFIG"
	source /usr/share/dev-scripts/incl/config_files
	source /usr/share/dev-scripts/incl/load_env
	set -x
	if [[ ! -f "$CONF_GIT" ]] 
	then	git_user=""
		tui-echo "What is your default code host:"
		select host in other $(cd "$this_dir";ls);do break;done
		case $host in
		other)	name=$(tui-read "What is its name (no spaces!):")
			user=$(tui-read "What is the accountname:")
			tui-echo
		#	tui-echo "Be aware you probably will need to change this value on a 'per project' matter." "Sorry."
			URL=$(tui-read "What is the base URL:")
			tui-echo
			tui-echo "This is just for convenience."
			URL2=$(tui-read "What is the full URL to add a new project there:")
			cat > "$this_dir/$name" << EOF
name=$name
user=$user
URL=\"$URL\"
URL_NEW=\"$URL2\"
EOF
			host=$name
			;;
	#	*)	git_user=$(tui-read "What is your ")	;;
		esac

		source "$this_dir/$host"
		[[ ! -f "$CONF_GIT" ]] && cat > "$CONF_GIT" << EOF
GIT_ID=$name
GIT_USER=$user
GIT_URL=\"$URL\"
GIT_NEW=\"$URL_NEW\"
EOF
	fi
	source "$CONF_GIT"
	set +x
	exit
#
#	Catching Arguments
#
	# A ':' after a char indicates that this option requires an argument
	while getopts "h" opt
	do 	case $opt in
		h)	printf "$help_text"
			exit $RET_HELP
			;;
		esac
	done
	shift $(($OPTIND - 1))
#
#	Display & Action
#
	#tui-header "${APP^}:$ME ($script_version)" "$(date +'%F %T')"
	tui-title "$TITLE"
	tui-echo "Hello $USER, welcome to set up your developement environment"
	tui-echo "You will be asked a few questions and introduced to this standard"
	tui-echo
	
	tui-echo "Where is your projects holding dir?"
	newdir=$(tui-read "Leave empty for: '$DIR_PRJS'")
	[[ -z $newdir ]] || tui-conf-set $CONFIG DIR_PRJS $newdir
	tui-echo
	
	#echo $CONFIG_DIR
	tui-echo "Please select your default git handler"
	select newVAL in $(cd "$CONFIG_DIR/gitinfo/" ; ls );do break;done
	[[ ! -z $newVAL ]] && \
		source $CONFIG_DIR/gitinfo/$newVAL && \
		tui-conf-set $CONF_GIT GIT_ID $name && \
		tui-conf-set $CONF_GIT GIT_URL $URL
	tui-echo
	
	tui-echo "What is your GIT Username on $name?"
	newVAL=$(tui-read "Leave empty for '$GIT_USER':")
	[[ -z $newVAL ]] || tui-conf-set "$CONF_GIT" GIT_USER "$newVAL"
	# TODO
	tui-echo "TODO: Save to $HOME/.gitconf if not exists yet!" \
		"Better yet, read it out if exists.. (low prio)"
	tui-echo
	
	#tui-echo "
	if tui-yesno "Do you have a FAS account?"
	then	tui-conf-set $CONFIG hasFAS true
		tui-yesno "Treat all projects as FAS projects?" && \
			ret=true || ret=false
		tui-conf-set $CONFIG useFAS $ret
	fi
	tui-echo
	
	exit
	
	tui-echo ""
	newVAL=$(tui-read "")
	[[ -z $newVAL ]] || tui-conf-set $CONFIG DIR_PRJS $newVAL
	tui-echo
	
