#!/bin/bash
# ------------------------------------------------------------------------
#
# Copyright (c) 2014 by Simon Arjuna Erat (sea)  <erat.simon@gmail.com>
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ------------------------------------------------------------------------
#
#	
	source /etc/tui/tui.conf
	source /etc/os-release
	source /etc/tui/apps.conf
	[[ 0 -ne $UID ]] || \
		source $HOME/.config/tui/apps.conf
		
	script_version=0.2
#
#	Title
#
	title="$OA_TITLE - Mock Handler - Add default settings"
	tui-title "$title ($script_version)"
#
#	Variables
#
	case $# in
	5)	shift 3 ;;
	esac
	
	while getopts "vs" opts
	do 	case $opts in
		v)	beVerbose=true
			NONVERBOSE=""
			;;
		s)	dummy=$opts	;;
		esac
	done
	shift $(($OPTIND - 1))
	
	if [[ -z "$4" ]] # || [[ ! -z "$LBL" ]]
	then	if [[ -d "$DIR_CFG/$1" ]]
		then	LBL="$1"
		else	tui-echo "Please select the label to work with:"
			select LBL in $(cd "$DIR_CFG";ls|$GREP -v \.);do break;done
		fi
	else	LBL="$4"
	fi
	
	#source "$CONF_RPM"
	source "$DIR_CFG/$LBL/$LBL.conf"
	cp -f $CONF_MOCK "$DIR_CFG/$LBL/mock.conf"
	tui-edit "$DIR_CFG/$LBL/mock.conf"